
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - C:/Users/ahmed/Desktop/Projects/demo_app:/var/www/html

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret